include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: false
    strict-inference: false

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
    use_super_parameters: true
    prefer_single_quotes: true
    require_trailing_commas: false
    lines_longer_than_80_chars: false
